### ISSUE TITLE
Hobbing setup

### ISSUE THREAD

**Issue by digiexchris** [jschoch/ESPels#18]
I'm super interested in your setup for hobbing, do you have any pictures of the machine setup to do work?

**Comment by jschoch** [comment]
it is actually setup with a completely different firmware right now.  the logic doesn't map the same but I should be able to integrate it.  I want to control the hob as well as just do basic indexing with it.

here's a video I made

https://youtu.be/YwU1n3QAViU

**Comment by digiexchris** [comment]
very cool, thanks! That makes sense to be separate firmware, different use cases and it's causing me different kinds of ideas, like a UI to enter divisions for normal dividing head use.
