### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by digiexchris** [jschoch/ESPels#19]
Espressif has documentation on unit testing, I will work on getting this working in platformio.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/unit-tests.html

**Comment by jschoch** [comment]
sweet!  I"m working on cleaning up the unused vars and auditing the json doc variables are in fact used

**Comment by jschoch** [comment]
basic gear tests are now here: https://github.com/jschoch/ESPels/blob/dev/test/test_stepper/test_stepper.cpp

need to add tests for the state machine in general as well as bounce mode, and feed mode
