### ISSUE TITLE
Broaching mode

### ISSUE THREAD

**Issue by digiexchris** [jschoch/ESPels#28]
Just a simple addition to bounce mode where it continually does a normal feed to depth, rapids out, pauses for a configurable amount of time, and runs it in again. It would need to not be synced to the spindle. I would use this to help me broach keyways on the lathe. I'd just fed in a thou or so when it withdraws from the bore between passes.

**Comment by jschoch** [comment]
this is doable!

**Comment by jschoch** [comment]
This is implemented as bounce mode in the jog tab.
